// Mozilla Public License Version 2.0

// WARNING: This file has automatically been generated on Fri, 17 Jan 2020 20:00:08 MSK.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package open62541

/*
#cgo LDFLAGS: -lopen62541
#include "open62541/architecture_base.h"
#include "open62541/architecture_definitions.h"
#include "open62541/architecture_functions.h"
#include "open62541/client_config_default.h"
#include "open62541/client_config.h"
#include "open62541/client.h"
#include "open62541/client_highlevel_async.h"
#include "open62541/client_highlevel.h"
#include "open62541/client_subscriptions.h"
#include "open62541/config.h"
#include "open62541/constants.h"
#include "open62541/ms_stdint.h"
#include "open62541/network_tcp.h"
#include "open62541/nodeids.h"
#include "open62541/server_config_default.h"
#include "open62541/server_config.h"
#include "open62541/server.h"
#include "open62541/server_pubsub.h"
#include "open62541/statuscodes.h"
#include "open62541/types_generated.h"
#include "open62541/types_generated_handling.h"
#include "open62541/types.h"
#include "open62541/util.h"
#include "open62541/ziptree.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// NodeIdType as declared in open62541/types.h:308
type NodeIdType int32

// NodeIdType enumeration from open62541/types.h:308
const ()

const ()

const ()

const ()

const ()

const ()

const ()

// _SocketType as declared in bits/socket_type.h:24
type _SocketType int32

// _SocketType enumeration from bits/socket_type.h:24
const ()

const ()

const ()

const ()

const ()

const ()

// TcpCaState as declared in netinet/tcp.h:216
type TcpCaState int32

// TcpCaState enumeration from netinet/tcp.h:216
const ()

const ()
