// Mozilla Public License Version 2.0

// WARNING: This file has automatically been generated on Fri, 17 Jan 2020 16:51:20 MSK.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package open62541 provides Go bindings for https://github.com/open62541/open62541
*/
package open62541
