// Mozilla Public License Version 2.0

// WARNING: This file has automatically been generated on Thu, 02 Apr 2020 09:44:57 MSK.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package open62541 provides Go bindings for https://github.com/open62541/open62541
*/
package open62541
