// Mozilla Public License Version 2.0

// WARNING: This file has automatically been generated on Thu, 02 Apr 2020 14:28:43 MSK.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package open62541

/*
#cgo LDFLAGS: -lopen62541
#include "open62541/architecture_base.h"
#include "open62541/architecture_definitions.h"
#include "open62541/architecture_functions.h"
#include "open62541/client_config_default.h"
#include "open62541/client_config.h"
#include "open62541/client.h"
#include "open62541/client_highlevel_async.h"
#include "open62541/client_highlevel.h"
#include "open62541/client_subscriptions.h"
#include "open62541/config.h"
#include "open62541/constants.h"
#include "open62541/ms_stdint.h"
#include "open62541/network_tcp.h"
#include "open62541/nodeids.h"
#include "open62541/server_config_default.h"
#include "open62541/server_config.h"
#include "open62541/server.h"
#include "open62541/server_pubsub.h"
#include "open62541/statuscodes.h"
#include "open62541/types_generated.h"
#include "open62541/types_generated_handling.h"
#include "open62541/types.h"
#include "open62541/util.h"
#include "open62541/ziptree.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// ServerConfig as declared in open62541/server.h:25
type ServerConfig C.UA_ServerConfig

// Server as declared in open62541/server.h:28
type Server C.UA_Server

// NodeTypeLifecycle as declared in open62541/server.h:730
type NodeTypeLifecycle C.UA_NodeTypeLifecycle

// StatusCode type as declared in open62541/types.h:138
type StatusCode uint32

// String as declared in open62541/types.h:155
type String C.UA_String

// DateTime type as declared in open62541/types.h:197
type DateTime int

// Guid as declared in open62541/types.h:256
type Guid C.UA_Guid

// ByteString as declared in open62541/types.h:266
type ByteString C.UA_String

// XmlElement as declared in open62541/types.h:300
type XmlElement C.UA_String

// NodeId as declared in open62541/types.h:326
type NodeId C.UA_NodeId

// ExpandedNodeId as declared in open62541/types.h:393
type ExpandedNodeId C.UA_ExpandedNodeId

// QualifiedName as declared in open62541/types.h:454
type QualifiedName C.UA_QualifiedName

// LocalizedText as declared in open62541/types.h:484
type LocalizedText C.UA_LocalizedText

// NumericRange as declared in open62541/types.h:517
type NumericRange C.UA_NumericRange

// DataType as declared in open62541/types.h:559
type DataType C.UA_DataType

// Variant as declared in open62541/types.h:578
type Variant C.UA_Variant

// DataValue as declared in open62541/types.h:752
type DataValue C.UA_DataValue

// DiagnosticInfo as declared in open62541/types.h:774
type DiagnosticInfo C.UA_DiagnosticInfo

// ObjectAttributes as declared in open62541/types_generated.h:2036
type ObjectAttributes struct {
	SpecifiedAttributes uint32
	DisplayName         LocalizedText
	Description         LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
	EventNotifier       byte
	refe8e3a938         *C.UA_ObjectAttributes
	allocse8e3a938      interface{}
}

// VariableAttributes as declared in open62541/types_generated.h:2059
type VariableAttributes struct {
	SpecifiedAttributes     uint32
	DisplayName             LocalizedText
	Description             LocalizedText
	WriteMask               uint32
	UserWriteMask           uint32
	Value                   Variant
	DataType                NodeId
	ValueRank               int32
	ArrayDimensionsSize     uint
	ArrayDimensions         *uint32
	AccessLevel             byte
	UserAccessLevel         byte
	MinimumSamplingInterval float64
	Historizing             bool
	refd219e026             *C.UA_VariableAttributes
	allocsd219e026          interface{}
}

// ObjectTypeAttributes as declared in open62541/types_generated.h:2090
type ObjectTypeAttributes struct {
	SpecifiedAttributes uint32
	DisplayName         LocalizedText
	Description         LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
	IsAbstract          bool
	refe0f167e4         *C.UA_ObjectTypeAttributes
	allocse0f167e4      interface{}
}

// WriteValue as declared in open62541/types_generated.h:3150
type WriteValue struct {
	NodeId         NodeId
	AttributeId    uint32
	IndexRange     String
	Value          DataValue
	ref4be23793    *C.UA_WriteValue
	allocs4be23793 interface{}
}
