// Mozilla Public License Version 2.0

// WARNING: This file has automatically been generated on Tue, 31 Mar 2020 17:03:50 MSK.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package open62541

/*
#cgo LDFLAGS: -lopen62541
#include "open62541/architecture_base.h"
#include "open62541/architecture_definitions.h"
#include "open62541/architecture_functions.h"
#include "open62541/client_config_default.h"
#include "open62541/client_config.h"
#include "open62541/client.h"
#include "open62541/client_highlevel_async.h"
#include "open62541/client_highlevel.h"
#include "open62541/client_subscriptions.h"
#include "open62541/config.h"
#include "open62541/constants.h"
#include "open62541/ms_stdint.h"
#include "open62541/network_tcp.h"
#include "open62541/nodeids.h"
#include "open62541/server_config_default.h"
#include "open62541/server_config.h"
#include "open62541/server.h"
#include "open62541/server_pubsub.h"
#include "open62541/statuscodes.h"
#include "open62541/types_generated.h"
#include "open62541/types_generated_handling.h"
#include "open62541/types.h"
#include "open62541/util.h"
#include "open62541/ziptree.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// ServerConfig as declared in open62541/server.h:25
type ServerConfig C.UA_ServerConfig

// Server as declared in open62541/server.h:28
type Server C.UA_Server

// Boolean type as declared in open62541/types.h:49
type Boolean bool

// Double type as declared in open62541/types.h:128
type Double float64

// String as declared in open62541/types.h:155
type String C.UA_String

// ByteString as declared in open62541/types.h:266
type ByteString C.UA_String

// NodeId as declared in open62541/types.h:326
type NodeId C.UA_NodeId

// QualifiedName as declared in open62541/types.h:454
type QualifiedName C.UA_QualifiedName

// LocalizedText as declared in open62541/types.h:484
type LocalizedText C.UA_LocalizedText

// DataType as declared in open62541/types.h:559
type DataType C.UA_DataType

// Variant as declared in open62541/types.h:578
type Variant C.UA_Variant

// Uint64T type as declared in bits/stdint-uintn.h:27
type Uint64T uint

// Int64T type as declared in bits/stdint-intn.h:27
type Int64T int

// ObjectAttributes as declared in open62541/types_generated.h:2036
type ObjectAttributes struct {
	SpecifiedAttributes uint32
	DisplayName         LocalizedText
	Description         LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
	EventNotifier       byte
	refe8e3a938         *C.UA_ObjectAttributes
	allocse8e3a938      interface{}
}

// VariableAttributes as declared in open62541/types_generated.h:2059
type VariableAttributes struct {
	SpecifiedAttributes     uint32
	DisplayName             LocalizedText
	Description             LocalizedText
	WriteMask               uint32
	UserWriteMask           uint32
	Value                   Variant
	DataType                NodeId
	ValueRank               int32
	ArrayDimensionsSize     uint
	ArrayDimensions         *uint32
	AccessLevel             byte
	UserAccessLevel         byte
	MinimumSamplingInterval Double
	Historizing             Boolean
	refd219e026             *C.UA_VariableAttributes
	allocsd219e026          interface{}
}
